services:
  postgres:
    image: pgvector/pgvector:0.8.5-pg18-trixie
    container_name: news-postgres
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U news -d news" ]
      interval: 5s
      timeout: 5s
      retries: 10
  lgtm:
    image: grafana/otel-lgtm:0.29.2
    container_name: observability-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

volumes:
  postgres18_data: