spring:
  application:
    name: news


  datasource:
    url: jdbc:h2:mem:newsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1



  open telemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

  otlp:
    metrics:
      export:
        enabled: false



logging:
  level:
    liquibase: debug
    sql: debug
    org.springframework.security: debug



